export type Product = {
  id: string;
  name: string;
  category: "Chair" | "Desk" | "Sofa";
  price: string;
  description: string;
  image: string;
  tag?: string;
};

export const products: Product[] = [
  // --- CHAIRS ---
  {
    id: "m250",
    name: "SIT-M250",
    category: "Chair",
    price: "Contact for pricing",
    description: "Modern mid-back task chair with breathable mesh and ergonomic lumbar support. Ideal for dynamic work environments.",
    image: "/products/chairs/m250.jpg",
    tag: "New",
  },
  {
    id: "m350bk",
    name: "SIT-M350 Black",
    category: "Chair",
    price: "Contact for pricing",
    description: "Sleek black mesh executive chair with synchronized tilt mechanism and adjustable armrests.",
    image: "/products/chairs/m350bk.jpg",
    tag: "Bestseller",
  },
  {
    id: "m350gr",
    name: "SIT-M350 Grey",
    category: "Chair",
    price: "Contact for pricing",
    description: "Grey mesh executive chair with synchronized tilt mechanism and adjustable armrests.",
    image: "/products/chairs/m350gr.jpg",
  },
  {
    id: "m750bk",
    name: "SIT-M750 Black",
    category: "Chair",
    price: "Contact for pricing",
    description: "Premium high-back executive chair in black. Full lumbar support, headrest, and multi-function mechanism.",
    image: "/products/chairs/m750bk.jpg",
    tag: "Popular",
  },
  {
    id: "m750gr",
    name: "SIT-M750 Grey",
    category: "Chair",
    price: "Contact for pricing",
    description: "Premium high-back executive chair in grey. Full lumbar support, headrest, and multi-function mechanism.",
    image: "/products/chairs/m750gr.jpg",
  },
  {
    id: "m900bk",
    name: "SIT-M900 Black",
    category: "Chair",
    price: "Contact for pricing",
    description: "Top-tier ergonomic chair with advanced lumbar adjustment, 4D armrests, and breathable mesh for all-day comfort.",
    image: "/products/chairs/m900bk.jpg",
    tag: "New",
  },
  {
    id: "m180b",
    name: "SIT-M180B",
    category: "Chair",
    price: "Contact for pricing",
    description: "Compact mesh task chair with contoured backrest and height adjustment. Perfect for focused work sessions.",
    image: "/products/chairs/m180b.jpg",
  },
  {
    id: "m275",
    name: "SIT-M275",
    category: "Chair",
    price: "Contact for pricing",
    description: "Mid-back office chair with foam seat, mesh back and durable nylon base. A reliable everyday workhorse.",
    image: "/products/chairs/m275.jpg",
  },
  {
    id: "m390",
    name: "SIT-M390",
    category: "Chair",
    price: "Contact for pricing",
    description: "Executive mesh chair with butterfly mechanism, adjustable headrest, and padded armrests.",
    image: "/products/chairs/m390.jpg",
  },
  {
    id: "m500",
    name: "SIT-M500",
    category: "Chair",
    price: "Contact for pricing",
    description: "Full-mesh ergonomic chair with independent seat depth adjustment and 3D armrests.",
    image: "/products/chairs/m500.jpg",
  },
  {
    id: "sec35bk",
    name: "SIT-SEC35 Black",
    category: "Chair",
    price: "Contact for pricing",
    description: "Classic mesh back chair with black nylon frame. Lightweight, stackable, and built for multi-use spaces.",
    image: "/products/chairs/sec35bk.jpg",
  },
  {
    id: "sec380bk",
    name: "SIT-SEC380 Black",
    category: "Chair",
    price: "Contact for pricing",
    description: "Mesh back and fabric seat combination chair. Ergonomic design suited for extended office use.",
    image: "/products/chairs/sec380bk.jpg",
  },
  {
    id: "8322h-bk",
    name: "8322H Black",
    category: "Chair",
    price: "Contact for pricing",
    description: "Classic high-back executive chair with PU leather seat and chrome base. Timeless professional aesthetic.",
    image: "/products/chairs/8322h-bk.jpg",
  },
  {
    id: "9373h-fabric",
    name: "9373H Fabric",
    category: "Chair",
    price: "Contact for pricing",
    description: "High-back fabric office chair with ergonomic curves, height adjustment, and rocking mechanism.",
    image: "/products/chairs/9373h-fabric.jpg",
  },

  // --- DESKS ---
  {
    id: "d295",
    name: "SIT-D295",
    category: "Desk",
    price: "Contact for pricing",
    description: "Clean-lined executive desk with generous surface area and integrated cable management.",
    image: "/products/desks/d295.jpg",
    tag: "Popular",
  },
  {
    id: "d380",
    name: "SIT-D380",
    category: "Desk",
    price: "Contact for pricing",
    description: "Modern L-shaped workstation with ample surface space and powder-coated steel legs.",
    image: "/products/desks/d380.jpg",
  },
  {
    id: "d385",
    name: "SIT-D385",
    category: "Desk",
    price: "Contact for pricing",
    description: "Contemporary executive desk with sleek panel base and refined finish options.",
    image: "/products/desks/d385.jpg",
  },
  {
    id: "d450",
    name: "SIT-D450",
    category: "Desk",
    price: "Contact for pricing",
    description: "Spacious double-pedestal executive desk with lockable drawers and premium wood veneer top.",
    image: "/products/desks/d450.jpg",
    tag: "Bestseller",
  },
  {
    id: "wk22",
    name: "SIT-WK22",
    category: "Desk",
    price: "Contact for pricing",
    description: "Compact open workstation with integrated privacy screen. Perfect for call centers and open-plan offices.",
    image: "/products/desks/wk22.jpg",
  },
  {
    id: "wk24",
    name: "SIT-WK24",
    category: "Desk",
    price: "Contact for pricing",
    description: "Modular workstation system with configurable layout options. Scales with your team.",
    image: "/products/desks/wk24.jpg",
  },
  {
    id: "wk42",
    name: "SIT-WK42",
    category: "Desk",
    price: "Contact for pricing",
    description: "Four-seat open workstation bench with central cable tray and acoustic divider ready.",
    image: "/products/desks/wk42.jpg",
  },
  {
    id: "repdark",
    name: "SIT-REP Reception Dark",
    category: "Desk",
    price: "Contact for pricing",
    description: "Curved reception desk in dark finish with LED accent lighting. Makes a commanding first impression.",
    image: "/products/desks/repdark.jpg",
    tag: "New",
  },
  {
    id: "repwhite",
    name: "SIT-REP Reception White",
    category: "Desk",
    price: "Contact for pricing",
    description: "Curved reception desk in white gloss with integrated counter height. Sleek and professional.",
    image: "/products/desks/repwhite.jpg",
  },
  {
    id: "electric",
    name: "SIT Electric Height Desk",
    category: "Desk",
    price: "Contact for pricing",
    description: "Electric sit-stand desk with dual motors, memory presets, and anti-collision detection. A healthier workday starts here.",
    image: "/products/desks/electric.jpg",
    tag: "Popular",
  },

  // --- SOFAS ---
  {
    id: "aura-bg",
    name: "SIT-AURA Beige",
    category: "Sofa",
    price: "Contact for pricing",
    description: "Contemporary three-seat lounge sofa in beige with sculpted cushions and solid wood legs. Elevates any reception or lounge area.",
    image: "/products/sofas/aura-bg.jpg",
    tag: "Bestseller",
  },
  {
    id: "elisse-bl",
    name: "SIT-ELISSE Blue",
    category: "Sofa",
    price: "Contact for pricing",
    description: "Statement lounge sofa in rich blue fabric with tapered legs. Bold color meets refined silhouette.",
    image: "/products/sofas/elisse-bl.jpg",
    tag: "New",
  },
  {
    id: "lumina-bg",
    name: "SIT-LUMINA Beige",
    category: "Sofa",
    price: "Contact for pricing",
    description: "Low-profile lounge sofa with clean lines and channel-stitched cushions. Modern and inviting.",
    image: "/products/sofas/lumina-bg.jpg",
  },
  {
    id: "louren-bg",
    name: "SIT-LOUREN Beige",
    category: "Sofa",
    price: "Contact for pricing",
    description: "Compact two-seat lounge sofa with round armrests and premium fabric upholstery.",
    image: "/products/sofas/louren-bg.jpg",
  },
  {
    id: "ondara-bg",
    name: "SIT-ONDARA Beige",
    category: "Sofa",
    price: "Contact for pricing",
    description: "Curved modular lounge sofa with deep seating and plush cushions. Designed for collaboration zones.",
    image: "/products/sofas/ondara-bg.jpg",
    tag: "Popular",
  },
  {
    id: "ovalia-bg",
    name: "SIT-OVALIA Beige",
    category: "Sofa",
    price: "Contact for pricing",
    description: "Oval-backed accent sofa with distinctive silhouette. A design-forward statement for modern lobbies.",
    image: "/products/sofas/ovalia-bg.jpg",
  },
  {
    id: "tessa-bg",
    name: "SIT-TESSA Beige",
    category: "Sofa",
    price: "Contact for pricing",
    description: "Three-seat sofa with button-tufted back and tapered walnut legs. Classic elegance for professional spaces.",
    image: "/products/sofas/tessa-bg.jpg",
  },
  {
    id: "velora-br",
    name: "SIT-VELORA Brown",
    category: "Sofa",
    price: "Contact for pricing",
    description: "Luxurious lounge sofa in warm brown with wrap-around armrests and deep seat cushions.",
    image: "/products/sofas/velora-br.jpg",
  },
];
